name: GospelToolkit
options:
  bundleIdPrefix: com.gospeltoolkit
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
settings:
  SWIFT_VERSION: "6.0"
  SWIFT_STRICT_CONCURRENCY: targeted
packages:
  ReadiumSwiftToolkit:
    url: https://github.com/readium/swift-toolkit
    version: 3.6.0
targets:
  GospelToolkit:
    type: application
    platform: iOS
    sources:
      - path: GospelToolkit
        excludes:
          - "Data/*.json"
      - path: GospelToolkit/Data
        buildPhase: resources
        type: group
      - path: GospelToolkit/Resources/Books
        buildPhase: resources
        type: group
    settings:
      INFOPLIST_GENERATION_MODE: GeneratedFile
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: 1
      GENERATE_INFOPLIST_FILE: true
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      INFOPLIST_KEY_CFBundleDisplayName: "福音工具箱"
      PRODUCT_BUNDLE_IDENTIFIER: com.gospeltoolkit.app
      SWIFT_EMIT_LOC_STRINGS: true
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGNING_ALLOWED: NO
    dependencies:
      - package: ReadiumSwiftToolkit
        product: ReadiumShared
      - package: ReadiumSwiftToolkit
        product: ReadiumStreamer
      - package: ReadiumSwiftToolkit
        product: ReadiumNavigator
      - package: ReadiumSwiftToolkit
        product: ReadiumOPDS
      - package: ReadiumSwiftToolkit
        product: ReadiumAdapterGCDWebServer
