import BookList from '@/components/BookList';
import type { BibleBook } from '@/components/BookList';

export const metadata = {
  title: '历史书 - 旧约导读 - 真理磐石',
  description: '旧约历史书导读：从约书亚记到以斯帖记，共12卷。',
};

const books: BibleBook[] = [
  {
    id: 'joshua',
    name_zh: '约书亚记',
    name_en: 'Joshua',
    author_zh: '约书亚',
    author_en: 'Joshua',
    date: '约公元前1400-1370年',
    date_en: 'c. 1400–1370 BC',
    theme_zh: '得地为业——神应许的成就',
    theme_en: 'Possessing the Land — The Fulfillment of God\'s Promise',
    summary_zh: '约书亚记记载以色列人在约书亚带领下进入迦南应许之地，征服并分配土地。神信守祂对亚伯拉罕的应许，没有一句话落空。',
    summary_en: 'Joshua records Israel\'s conquest and settlement of the Promised Land under Joshua\'s leadership. God kept every promise He made to Abraham — not one word failed.',
    keyVerse_zh: '至于我和我家，我们必定事奉耶和华。',
    keyVerse_en: 'But as for me and my house, we will serve the LORD.',
    keyRef: '约书亚记 24:15 / Joshua 24:15',
  },
  {
    id: 'judges',
    name_zh: '士师记',
    name_en: 'Judges',
    author_zh: '传统认为撒母耳',
    author_en: 'Traditionally Samuel',
    date: '约公元前1050年',
    date_en: 'c. 1050 BC',
    theme_zh: '堕落循环——各人任意而行的时代',
    theme_en: 'The Cycle of Sin — Everyone Did What Was Right in Their Own Eyes',
    summary_zh: '士师记描绘以色列人反复犯罪、受苦、呼求、得拯救的循环，揭示人离弃神后的败坏。全书指向对一位公义之王的迫切需要。',
    summary_en: 'Judges portrays the repeated cycle of sin, oppression, crying out, and deliverance in Israel, revealing humanity\'s corruption apart from God. The whole book points to the desperate need for a righteous King.',
    keyVerse_zh: '那时以色列中没有王，各人任意而行。',
    keyVerse_en: 'In those days there was no king in Israel. Everyone did what was right in his own eyes.',
    keyRef: '士师记 21:25 / Judges 21:25',
  },
  {
    id: 'ruth',
    name_zh: '路得记',
    name_en: 'Ruth',
    author_zh: '传统认为撒母耳',
    author_en: 'Traditionally Samuel',
    date: '约公元前1010年',
    date_en: 'c. 1010 BC',
    theme_zh: '忠爱与救赎——至近亲属的预表',
    theme_en: 'Loyal Love and Redemption — A Foreshadowing of the Kinsman-Redeemer',
    summary_zh: '路得记在士师时代的黑暗中展现了一个信心与忠爱的美好故事。摩押女子路得归信耶和华，波阿斯作为至近亲属救赎她，预表基督对教会的救赎。',
    summary_en: 'Ruth presents a beautiful story of faith and loyal love amid the darkness of the judges. Ruth the Moabitess turns to the LORD, and Boaz as kinsman-redeemer foreshadows Christ\'s redemption of the Church.',
    keyVerse_zh: '你的国就是我的国，你的神就是我的神。',
    keyVerse_en: 'Your people shall be my people, and your God my God.',
    keyRef: '路得记 1:16 / Ruth 1:16',
  },
  {
    id: '1samuel',
    name_zh: '撒母耳记上',
    name_en: '1 Samuel',
    author_zh: '撒母耳等',
    author_en: 'Samuel and others',
    date: '约公元前1050-930年',
    date_en: 'c. 1050–930 BC',
    theme_zh: '从士师到君王——神的主权与人的选择',
    theme_en: 'From Judges to Kings — God\'s Sovereignty and Human Choice',
    summary_zh: '撒母耳记上记载以色列从士师时代过渡到君王时代，撒母耳膏立扫罗和大卫。扫罗因悖逆被废，合神心意的大卫被拣选为王。',
    summary_en: 'First Samuel records Israel\'s transition from the judges to the monarchy, with Samuel anointing Saul and David. Saul is rejected for disobedience, and David, a man after God\'s heart, is chosen as king.',
    keyVerse_zh: '耶和华不像人看人：人是看外貌；耶和华是看内心。',
    keyVerse_en: 'For the LORD sees not as man sees: man looks on the outward appearance, but the LORD looks on the heart.',
    keyRef: '撒母耳记上 16:7 / 1 Samuel 16:7',
  },
  {
    id: '2samuel',
    name_zh: '撒母耳记下',
    name_en: '2 Samuel',
    author_zh: '佚名',
    author_en: 'Anonymous',
    date: '约公元前930年',
    date_en: 'c. 930 BC',
    theme_zh: '大卫的国度——恩典与管教',
    theme_en: 'David\'s Kingdom — Grace and Discipline',
    summary_zh: '撒母耳记下记载大卫作王的辉煌与失败，神与大卫立约应许永远的国度。大卫犯罪后的悔改和神的管教，展现了恩典与公义的并行。',
    summary_en: 'Second Samuel records David\'s glorious reign and failures. God\'s covenant with David promises an everlasting kingdom. David\'s repentance after sin and God\'s discipline display the interplay of grace and justice.',
    keyVerse_zh: '你的家和你的国，必在我面前永远坚立。你的国位也必坚定，直到永远。',
    keyVerse_en: 'Your house and your kingdom shall be made sure forever before me. Your throne shall be established forever.',
    keyRef: '撒母耳记下 7:16 / 2 Samuel 7:16',
  },
  {
    id: '1kings',
    name_zh: '列王纪上',
    name_en: '1 Kings',
    author_zh: '传统认为耶利米',
    author_en: 'Traditionally Jeremiah',
    date: '约公元前560年',
    date_en: 'c. 560 BC',
    theme_zh: '所罗门的荣耀与国度的分裂',
    theme_en: 'Solomon\'s Glory and the Division of the Kingdom',
    summary_zh: '列王纪上记载所罗门的智慧和建殿的荣耀，随后因拜偶像导致国度分裂为南北两国。以利亚勇敢站立对抗巴力崇拜，呼召百姓归向真神。',
    summary_en: 'First Kings records Solomon\'s wisdom and the glory of the temple, followed by the kingdom\'s division due to idolatry. Elijah boldly confronts Baal worship, calling the people back to the true God.',
    keyVerse_zh: '耶和华是神！耶和华是神！',
    keyVerse_en: 'The LORD, he is God; the LORD, he is God.',
    keyRef: '列王纪上 18:39 / 1 Kings 18:39',
  },
  {
    id: '2kings',
    name_zh: '列王纪下',
    name_en: '2 Kings',
    author_zh: '传统认为耶利米',
    author_en: 'Traditionally Jeremiah',
    date: '约公元前560年',
    date_en: 'c. 560 BC',
    theme_zh: '亡国与被掳——悖逆的结局',
    theme_en: 'Exile — The Consequence of Rebellion',
    summary_zh: '列王纪下记载以色列和犹大二国逐步走向灭亡，北国被亚述所灭，南国被巴比伦所掳。纵然如此，神仍藉先知呼召百姓悔改，守护大卫的灯。',
    summary_en: 'Second Kings records the decline and fall of both kingdoms — Israel to Assyria and Judah to Babylon. Yet God continues calling His people to repentance through prophets, preserving David\'s lamp.',
    keyVerse_zh: '耶和华从以色列面前赶出的列国之民所行可憎的事，他却效法了。',
    keyVerse_en: 'He did what was evil in the sight of the LORD, according to the abominations of the nations.',
    keyRef: '列王纪下 17:8 / 2 Kings 17:8',
  },
  {
    id: '1chronicles',
    name_zh: '历代志上',
    name_en: '1 Chronicles',
    author_zh: '传统认为以斯拉',
    author_en: 'Traditionally Ezra',
    date: '约公元前450年',
    date_en: 'c. 450 BC',
    theme_zh: '大卫的敬拜与神的约',
    theme_en: 'David\'s Worship and God\'s Covenant',
    summary_zh: '历代志上从家谱开始，着重记载大卫如何安排敬拜、预备建殿材料，以及神与大卫所立的永约。全书强调正确的敬拜是国家蒙福的核心。',
    summary_en: 'First Chronicles begins with genealogies and focuses on David\'s arrangements for worship, temple preparations, and God\'s everlasting covenant with David. True worship is at the heart of national blessing.',
    keyVerse_zh: '你当将耶和华的名所当得的荣耀归给祂！',
    keyVerse_en: 'Ascribe to the LORD the glory due his name!',
    keyRef: '历代志上 16:29 / 1 Chronicles 16:29',
  },
  {
    id: '2chronicles',
    name_zh: '历代志下',
    name_en: '2 Chronicles',
    author_zh: '传统认为以斯拉',
    author_en: 'Traditionally Ezra',
    date: '约公元前450年',
    date_en: 'c. 450 BC',
    theme_zh: '圣殿、悔改与复兴',
    theme_en: 'The Temple, Repentance, and Revival',
    summary_zh: '历代志下从所罗门建殿开始，记载南国犹大诸王的兴衰。凡寻求耶和华的王就蒙福，离弃神的就受审判。最终以被掳归回的盼望作结。',
    summary_en: 'Second Chronicles begins with Solomon building the temple and records the rise and fall of Judah\'s kings. Those who seek the LORD are blessed; those who forsake Him face judgment. It ends with hope of return from exile.',
    keyVerse_zh: '这称为我名下的子民，若是自卑、祷告，寻求我的面，转离他们的恶行，我必从天上垂听，赦免他们的罪，医治他们的地。',
    keyVerse_en: 'If my people who are called by my name humble themselves, and pray and seek my face and turn from their wicked ways, then I will hear from heaven and will forgive their sin and heal their land.',
    keyRef: '历代志下 7:14 / 2 Chronicles 7:14',
  },
  {
    id: 'ezra',
    name_zh: '以斯拉记',
    name_en: 'Ezra',
    author_zh: '以斯拉',
    author_en: 'Ezra',
    date: '约公元前450年',
    date_en: 'c. 450 BC',
    theme_zh: '归回与重建——神信守应许',
    theme_en: 'Return and Restoration — God Keeps His Promises',
    summary_zh: '以斯拉记记载犹大人从巴比伦被掳归回，重建圣殿和恢复敬拜。以斯拉带领百姓回归神的律法，洁净信仰中的混杂。',
    summary_en: 'Ezra records the return of the exiles from Babylon, the rebuilding of the temple, and the restoration of worship. Ezra leads the people back to God\'s law, purifying their faith from foreign corruption.',
    keyVerse_zh: '以斯拉定志考究遵行耶和华的律法，又将律例典章教训以色列人。',
    keyVerse_en: 'For Ezra had set his heart to study the Law of the LORD, and to do it and to teach his statutes and rules in Israel.',
    keyRef: '以斯拉记 7:10 / Ezra 7:10',
  },
  {
    id: 'nehemiah',
    name_zh: '尼希米记',
    name_en: 'Nehemiah',
    author_zh: '尼希米',
    author_en: 'Nehemiah',
    date: '约公元前430年',
    date_en: 'c. 430 BC',
    theme_zh: '重建城墙——信心中的行动',
    theme_en: 'Rebuilding the Walls — Faith in Action',
    summary_zh: '尼希米记记载尼希米带领百姓在重重困难中重建耶路撒冷城墙，并与以斯拉一起带领属灵复兴。祷告与行动相结合是本书的突出特点。',
    summary_en: 'Nehemiah records the rebuilding of Jerusalem\'s walls amid great opposition, along with spiritual revival led by Nehemiah and Ezra. The combination of prayer and action is the hallmark of this book.',
    keyVerse_zh: '我们的神必为我们争战。',
    keyVerse_en: 'Our God will fight for us.',
    keyRef: '尼希米记 4:20 / Nehemiah 4:20',
  },
  {
    id: 'esther',
    name_zh: '以斯帖记',
    name_en: 'Esther',
    author_zh: '佚名',
    author_en: 'Anonymous',
    date: '约公元前460年',
    date_en: 'c. 460 BC',
    theme_zh: '神隐秘的护理——看不见的手',
    theme_en: 'God\'s Hidden Providence — The Unseen Hand',
    summary_zh: '以斯帖记虽未直接提及神的名字，却处处彰显祂奇妙的护理。以斯帖和末底改在面临灭族危机时凭信心行动，神翻转局面拯救祂的百姓。',
    summary_en: 'Though God\'s name is never mentioned, Esther reveals His marvelous providence throughout. Esther and Mordecai act in faith amid a genocidal threat, and God turns the tables to save His people.',
    keyVerse_zh: '焉知你得了王后的位分不是为现今的机会吗？',
    keyVerse_en: 'And who knows whether you have not come to the kingdom for such a time as this?',
    keyRef: '以斯帖记 4:14 / Esther 4:14',
  },
];

export default function HistoricalPage() {
  return (
    <BookList
      icon="⚔️"
      title_zh="历史书"
      title_en="Historical Books"
      desc_zh="旧约历史书记载了以色列从征服迦南到被掳归回的历史。在兴衰更替中，神始终信守祂的盟约，引导祂的百姓走向救赎的应许。"
      desc_en="The Historical Books record Israel's history from the conquest of Canaan to the return from exile. Through rise and fall, God remains faithful to His covenant, guiding His people toward the promise of redemption."
      gradient="from-emerald-600 to-teal-800"
      books={books}
      backHref="/old-testament"
      backLabel="返回旧约导读 Back to Old Testament"
    />
  );
}
