import BookList from '@/components/BookList';
import type { BibleBook } from '@/components/BookList';

export const metadata = {
  title: '保罗书信 - 新约导读 - 真理磐石',
  description: '保罗书信导读：从罗马书到腓利门书，共13卷。',
};

const books: BibleBook[] = [
  {
    id: 'romans',
    name_zh: '罗马书',
    name_en: 'Romans',
    author_zh: '使徒保罗',
    author_en: 'Apostle Paul',
    date: '约公元57年',
    date_en: 'c. AD 57',
    theme_zh: '因信称义——福音的全面阐述',
    theme_en: 'Justification by Faith — A Comprehensive Exposition of the Gospel',
    summary_zh: '罗马书是保罗神学的巅峰之作，系统地阐述了人的罪、神的义、因信称义、成圣、拣选与以色列的命运等核心教义。它被称为"基督教信仰的宪章"。',
    summary_en: 'Romans is the pinnacle of Paul\'s theology, systematically expounding human sin, God\'s righteousness, justification by faith, sanctification, election, and the destiny of Israel.',
    keyVerse_zh: '因为世人都犯了罪，亏缺了神的荣耀；如今却蒙神的恩典，因基督耶稣的救赎，就白白地称义。',
    keyVerse_en: 'For all have sinned and fall short of the glory of God, and are justified by his grace as a gift, through the redemption that is in Christ Jesus.',
    keyRef: '罗马书 3:23-24 / Romans 3:23–24',
  },
  {
    id: '1corinthians',
    name_zh: '哥林多前书',
    name_en: '1 Corinthians',
    author_zh: '使徒保罗',
    author_en: 'Apostle Paul',
    date: '约公元55年',
    date_en: 'c. AD 55',
    theme_zh: '教会的合一与圣洁',
    theme_en: 'Unity and Holiness in the Church',
    summary_zh: '保罗针对哥林多教会的分裂、道德败坏和属灵恩赐的滥用等问题，教导教会如何在多元文化的城市中活出圣洁。第13章的爱篇和第15章的复活论是全书的高峰。',
    summary_en: 'Paul addresses divisions, moral failures, and the misuse of spiritual gifts in Corinth. Chapter 13 on love and Chapter 15 on the resurrection are the climax.',
    keyVerse_zh: '如今常存的有信，有望，有爱这三样，其中最大的是爱。',
    keyVerse_en: 'So now faith, hope, and love abide, these three; but the greatest of these is love.',
    keyRef: '哥林多前书 13:13 / 1 Corinthians 13:13',
  },
  {
    id: '2corinthians',
    name_zh: '哥林多后书',
    name_en: '2 Corinthians',
    author_zh: '使徒保罗',
    author_en: 'Apostle Paul',
    date: '约公元56年',
    date_en: 'c. AD 56',
    theme_zh: '软弱中的刚强——使徒的职分与苦难',
    theme_en: 'Strength in Weakness — Apostolic Ministry and Suffering',
    summary_zh: '这是保罗最个人化的书信，为自己的使徒职分辩护，分享事奉中的苦难与安慰，教导信徒在软弱中经历神的大能。',
    summary_en: 'Paul\'s most personal letter, defending his apostolic ministry, sharing sufferings and comforts, and teaching believers to experience God\'s power in weakness.',
    keyVerse_zh: '祂对我说："我的恩典够你用的，因为我的能力是在人的软弱上显得完全。"',
    keyVerse_en: 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness."',
    keyRef: '哥林多后书 12:9 / 2 Corinthians 12:9',
  },
  {
    id: 'galatians',
    name_zh: '加拉太书',
    name_en: 'Galatians',
    author_zh: '使徒保罗',
    author_en: 'Apostle Paul',
    date: '约公元49年',
    date_en: 'c. AD 49',
    theme_zh: '基督里的自由——唯独恩典，唯独信心',
    theme_en: 'Freedom in Christ — Grace Alone, Faith Alone',
    summary_zh: '保罗激烈地反驳"靠行律法称义"的错谬教导，宣告人唯独靠恩典因信称义。这封书信被称为"基督徒自由的大宪章"，是宗教改革的重要根基。',
    summary_en: 'Paul passionately refutes justification by works of the law, declaring justification by grace through faith alone. Called "the Magna Carta of Christian liberty," it was foundational to the Reformation.',
    keyVerse_zh: '基督释放了我们，叫我们得以自由。所以要站立得稳，不要再被奴仆的轭挟制。',
    keyVerse_en: 'For freedom Christ has set us free; stand firm therefore, and do not submit again to a yoke of slavery.',
    keyRef: '加拉太书 5:1 / Galatians 5:1',
  },
  {
    id: 'ephesians',
    name_zh: '以弗所书',
    name_en: 'Ephesians',
    author_zh: '使徒保罗',
    author_en: 'Apostle Paul',
    date: '约公元61年',
    date_en: 'c. AD 61',
    theme_zh: '在基督里的丰盛——教会是基督的身体',
    theme_en: 'Riches in Christ — The Church as the Body of Christ',
    summary_zh: '以弗所书展示了神在基督里赐给信徒的一切属灵福气：拣选、救赎、圣灵的印记。后半部分教导合一、圣洁的生活并穿戴全副军装。',
    summary_en: 'Ephesians reveals every spiritual blessing in Christ: election, redemption, the seal of the Spirit. The second half teaches unity, holiness, and putting on the full armor of God.',
    keyVerse_zh: '你们得救是本乎恩，也因着信；这并不是出于自己，乃是神所赐的。',
    keyVerse_en: 'For by grace you have been saved through faith. And this is not your own doing; it is the gift of God.',
    keyRef: '以弗所书 2:8 / Ephesians 2:8',
  },
  {
    id: 'philippians',
    name_zh: '腓立比书',
    name_en: 'Philippians',
    author_zh: '使徒保罗',
    author_en: 'Apostle Paul',
    date: '约公元62年',
    date_en: 'c. AD 62',
    theme_zh: '在基督里的喜乐',
    theme_en: 'Joy in Christ',
    summary_zh: '保罗在罗马狱中写下这封"喜乐书信"，教导信徒无论环境如何都可以在基督里喜乐。2:6-11的基督颂歌是新约最伟大的基督论经文之一。',
    summary_en: 'Paul wrote this "letter of joy" from prison, teaching believers to rejoice in Christ regardless of circumstances. The Christ hymn in 2:6-11 is one of the greatest Christological passages.',
    keyVerse_zh: '你们要靠主常常喜乐！我再说，你们要喜乐！',
    keyVerse_en: 'Rejoice in the Lord always; again I will say, rejoice.',
    keyRef: '腓立比书 4:4 / Philippians 4:4',
  },
  {
    id: 'colossians',
    name_zh: '歌罗西书',
    name_en: 'Colossians',
    author_zh: '使徒保罗',
    author_en: 'Apostle Paul',
    date: '约公元61年',
    date_en: 'c. AD 61',
    theme_zh: '基督的至高超越——万有之首',
    theme_en: 'The Supremacy of Christ — Head over All',
    summary_zh: '保罗高举基督超越一切受造之物的至高地位，反驳混合犹太教和异教元素的"歌罗西异端"。1:15-20的基督颂是对基督神性最有力的宣告之一。',
    summary_en: 'Paul exalts Christ\'s supremacy over all creation, refuting the "Colossian heresy." The Christ hymn in 1:15-20 is one of the most powerful declarations of Christ\'s deity.',
    keyVerse_zh: '爱子是那不能看见之神的像，是首生的，在一切被造的以先。',
    keyVerse_en: 'He is the image of the invisible God, the firstborn of all creation.',
    keyRef: '歌罗西书 1:15 / Colossians 1:15',
  },
  {
    id: '1thessalonians',
    name_zh: '帖撒罗尼迦前书',
    name_en: '1 Thessalonians',
    author_zh: '使徒保罗',
    author_en: 'Apostle Paul',
    date: '约公元51年',
    date_en: 'c. AD 51',
    theme_zh: '在盼望中等候主再来',
    theme_en: 'Waiting for the Lord\'s Return in Hope',
    summary_zh: '帖撒罗尼迦前书是保罗最早的书信之一，鼓励初信者在逼迫中坚守信仰，教导关于主再来和已死圣徒复活的真理，激励圣洁警醒的生活。',
    summary_en: 'One of Paul\'s earliest letters, encouraging new believers under persecution, teaching about the Lord\'s return and the resurrection of deceased saints, and urging holy, watchful living.',
    keyVerse_zh: '因为主必亲自从天降临，有呼叫的声音和天使长的声音，又有神的号吹响；那在基督里死了的人必先复活。',
    keyVerse_en: 'For the Lord himself will descend from heaven with a cry of command, with the voice of an archangel, and with the sound of the trumpet of God. And the dead in Christ will rise first.',
    keyRef: '帖撒罗尼迦前书 4:16 / 1 Thessalonians 4:16',
  },
  {
    id: '2thessalonians',
    name_zh: '帖撒罗尼迦后书',
    name_en: '2 Thessalonians',
    author_zh: '使徒保罗',
    author_en: 'Apostle Paul',
    date: '约公元51-52年',
    date_en: 'c. AD 51–52',
    theme_zh: '主再来前的坚忍',
    theme_en: 'Perseverance before the Lord\'s Return',
    summary_zh: '保罗纠正关于主再来的错误观念，指出大罪人必先显露，鼓励信徒在等候中不可懈怠，要殷勤做工、持守所学的真道。',
    summary_en: 'Paul corrects misunderstandings about the Lord\'s return, teaches that the man of lawlessness must be revealed first, and urges believers to work diligently and hold to the truth.',
    keyVerse_zh: '弟兄们，你们行善不可丧志。',
    keyVerse_en: 'As for you, brothers, do not grow weary in doing good.',
    keyRef: '帖撒罗尼迦后书 3:13 / 2 Thessalonians 3:13',
  },
  {
    id: '1timothy',
    name_zh: '提摩太前书',
    name_en: '1 Timothy',
    author_zh: '使徒保罗',
    author_en: 'Apostle Paul',
    date: '约公元63-65年',
    date_en: 'c. AD 63–65',
    theme_zh: '教会秩序与牧者的职分',
    theme_en: 'Church Order and Pastoral Ministry',
    summary_zh: '保罗指导年轻的提摩太如何管理以弗所教会：设立长老执事、抵挡假教师、在敬虔上操练自己，作信徒的榜样。',
    summary_en: 'Paul instructs young Timothy on managing the church in Ephesus: appointing elders and deacons, combating false teachers, training in godliness, and being an example to believers.',
    keyVerse_zh: '不可叫人小看你年轻，总要在言语、行为、爱心、信心、清洁上，都作信徒的榜样。',
    keyVerse_en: 'Let no one despise you for your youth, but set the believers an example in speech, in conduct, in love, in faith, in purity.',
    keyRef: '提摩太前书 4:12 / 1 Timothy 4:12',
  },
  {
    id: '2timothy',
    name_zh: '提摩太后书',
    name_en: '2 Timothy',
    author_zh: '使徒保罗',
    author_en: 'Apostle Paul',
    date: '约公元67年',
    date_en: 'c. AD 67',
    theme_zh: '持守所信的道——保罗的遗嘱',
    theme_en: 'Guard the Faith — Paul\'s Final Testament',
    summary_zh: '提摩太后书是保罗殉道前的最后书信，嘱咐提摩太刚强壮胆、传扬正道、忍受苦难。"那美好的仗我已经打过了"是保罗一生的总结。',
    summary_en: 'Paul\'s final letter before martyrdom urges Timothy to be strong, preach the Word, and endure suffering. "I have fought the good fight" is Paul\'s summary of his life.',
    keyVerse_zh: '圣经都是神所默示的，于教训、督责、使人归正、教导人学义都是有益的。',
    keyVerse_en: 'All Scripture is breathed out by God and profitable for teaching, for reproof, for correction, and for training in righteousness.',
    keyRef: '提摩太后书 3:16 / 2 Timothy 3:16',
  },
  {
    id: 'titus',
    name_zh: '提多书',
    name_en: 'Titus',
    author_zh: '使徒保罗',
    author_en: 'Apostle Paul',
    date: '约公元63-65年',
    date_en: 'c. AD 63–65',
    theme_zh: '健全的教义与敬虔的生活',
    theme_en: 'Sound Doctrine and Godly Living',
    summary_zh: '保罗指导提多在克里特岛建立教会秩序，强调健全的教义必然产生敬虔的生活。神救众人的恩典已经显明，教训我们弃绝不敬虔的心。',
    summary_en: 'Paul instructs Titus to establish church order in Crete, emphasizing that sound doctrine produces godly living. The grace of God has appeared, training us to renounce ungodliness.',
    keyVerse_zh: '因为神救众人的恩典已经显明出来。',
    keyVerse_en: 'For the grace of God has appeared, bringing salvation for all people.',
    keyRef: '提多书 2:11 / Titus 2:11',
  },
  {
    id: 'philemon',
    name_zh: '腓利门书',
    name_en: 'Philemon',
    author_zh: '使徒保罗',
    author_en: 'Apostle Paul',
    date: '约公元61年',
    date_en: 'c. AD 61',
    theme_zh: '福音里的和好与饶恕',
    theme_en: 'Reconciliation and Forgiveness in the Gospel',
    summary_zh: '保罗为逃跑的奴隶阿尼西母求情，请求腓利门接纳他不再是奴仆而是亲爱的弟兄。这封短信彰显福音如何改变人际关系，带来真正的和好。',
    summary_en: 'Paul intercedes for the runaway slave Onesimus, asking Philemon to receive him no longer as a slave but as a beloved brother. This short letter demonstrates how the gospel transforms relationships.',
    keyVerse_zh: '他暂时离开你，或者是叫你永远得着他——不再是奴仆，乃是高过奴仆，是亲爱的兄弟。',
    keyVerse_en: 'For this perhaps is why he was parted from you for a while, that you might have him back forever, no longer as a bondservant but more than a bondservant, as a beloved brother.',
    keyRef: '腓利门书 1:15-16 / Philemon 1:15–16',
  },
];

export default function PaulinePage() {
  return (
    <BookList
      icon="✉️"
      title_zh="保罗书信"
      title_en="Pauline Epistles"
      desc_zh="使徒保罗写给各教会和同工的13封书信，系统阐述了因信称义、在基督里的自由、教会的合一与圣洁等福音核心真理，是基督教神学的根基。"
      desc_en="Paul's 13 letters to churches and co-workers systematically expound the core truths of the gospel — justification by faith, freedom in Christ, the unity and holiness of the Church — forming the foundation of Christian theology."
      gradient="from-indigo-600 to-blue-800"
      books={books}
      backHref="/new-testament"
      backLabel="返回新约导读 Back to New Testament"
    />
  );
}
