import BookList from '@/components/BookList';
import type { BibleBook } from '@/components/BookList';

export const metadata = {
  title: '小先知书 - 旧约导读 - 真理磐石',
  description: '小先知书导读：从何西阿书到玛拉基书，共12卷。',
};

const books: BibleBook[] = [
  {
    id: 'hosea',
    guideHref: '/old-testament/minor-prophets/hosea',
    name_zh: '何西阿书',
    name_en: 'Hosea',
    author_zh: '何西阿',
    author_en: 'Hosea',
    date: '约公元前750-715年',
    date_en: 'c. 750–715 BC',
    theme_zh: '不离不弃的爱——神对悖逆百姓的信实',
    theme_en: 'Unfailing Love — God\'s Faithfulness to a Rebellious People',
    summary_zh: '何西阿以自己与不忠妻子的婚姻比喻神与以色列的关系。尽管百姓如淫妇般背约，神的爱仍不离不弃，呼唤他们回转。',
    summary_en: 'Hosea\'s marriage to an unfaithful wife illustrates God\'s relationship with Israel. Though the people broke covenant like an adulteress, God\'s love remains steadfast, calling them to return.',
    keyVerse_zh: '我必聘你永远归我为妻，以仁义、公平、慈爱、怜悯聘你归我。',
    keyVerse_en: 'I will betroth you to me forever. I will betroth you to me in righteousness and in justice, in steadfast love and in mercy.',
    keyRef: '何西阿书 2:19 / Hosea 2:19',
  },
  {
    id: 'joel',
    guideHref: '/old-testament/minor-prophets/joel',
    name_zh: '约珥书',
    name_en: 'Joel',
    author_zh: '约珥',
    author_en: 'Joel',
    date: '约公元前835年（或更晚）',
    date_en: 'c. 835 BC (or later)',
    theme_zh: '耶和华的日子与圣灵的浇灌',
    theme_en: 'The Day of the LORD and the Outpouring of the Spirit',
    summary_zh: '约珥以蝗灾为背景呼吁百姓悔改，预言耶和华大而可畏的日子，并应许圣灵将浇灌在一切有血气的人身上——这预言在五旬节应验。',
    summary_en: 'Joel uses a locust plague to call the people to repentance, prophesies the great and awesome Day of the LORD, and promises the Spirit will be poured out on all flesh — fulfilled at Pentecost.',
    keyVerse_zh: '以后，我要将我的灵浇灌凡有血气的。',
    keyVerse_en: 'And it shall come to pass afterward, that I will pour out my Spirit on all flesh.',
    keyRef: '约珥书 2:28 / Joel 2:28',
  },
  {
    id: 'amos',
    guideHref: '/old-testament/minor-prophets/amos',
    name_zh: '阿摩司书',
    name_en: 'Amos',
    author_zh: '阿摩司',
    author_en: 'Amos',
    date: '约公元前760年',
    date_en: 'c. 760 BC',
    theme_zh: '社会公义——神恨恶虚伪的敬拜',
    theme_en: 'Social Justice — God Hates Hollow Worship',
    summary_zh: '牧人阿摩司被神差遣到北国以色列，严厉谴责富人欺压穷人、社会不义和虚伪的宗教。神要求的是公平如大水滚滚，使公义如江河滔滔。',
    summary_en: 'The shepherd Amos was sent by God to northern Israel, sternly condemning the oppression of the poor, social injustice, and hollow religion. God demands justice rolling down like waters and righteousness like an ever-flowing stream.',
    keyVerse_zh: '惟愿公平如大水滚滚，使公义如江河滔滔。',
    keyVerse_en: 'But let justice roll down like waters, and righteousness like an ever-flowing stream.',
    keyRef: '阿摩司书 5:24 / Amos 5:24',
  },
  {
    id: 'obadiah',
    guideHref: '/old-testament/minor-prophets/obadiah',
    name_zh: '俄巴底亚书',
    name_en: 'Obadiah',
    author_zh: '俄巴底亚',
    author_en: 'Obadiah',
    date: '约公元前586年后',
    date_en: 'c. after 586 BC',
    theme_zh: '审判骄傲——以东的结局',
    theme_en: 'Judgment on Pride — The Doom of Edom',
    summary_zh: '俄巴底亚书是旧约最短的书卷，宣告神对以东骄傲的审判。以东因在犹大遭难时幸灾乐祸而受罚，神的国度终将得胜。',
    summary_en: 'Obadiah is the shortest book of the Old Testament, announcing God\'s judgment on Edom\'s pride. Edom is punished for gloating over Judah\'s calamity. The kingdom shall be the LORD\'s.',
    keyVerse_zh: '国度就归耶和华了。',
    keyVerse_en: 'The kingdom shall be the LORD\'s.',
    keyRef: '俄巴底亚书 1:21 / Obadiah 1:21',
  },
  {
    id: 'jonah',
    guideHref: '/old-testament/minor-prophets/jonah',
    name_zh: '约拿书',
    name_en: 'Jonah',
    author_zh: '约拿',
    author_en: 'Jonah',
    date: '约公元前780年',
    date_en: 'c. 780 BC',
    theme_zh: '神的怜悯超越国界',
    theme_en: 'God\'s Mercy Beyond Borders',
    summary_zh: '约拿书记载先知约拿逃避使命、被大鱼吞吐后前往尼尼微传道的故事。尼尼微全城悔改蒙恩，彰显神对万民的怜悯远超人的狭隘。',
    summary_en: 'Jonah records the prophet\'s flight from his mission, his time in the great fish, and his preaching to Nineveh. The entire city repents and is spared, displaying God\'s mercy for all nations far beyond human narrowness.',
    keyVerse_zh: '你是有恩典、有怜悯的神，不轻易发怒，有丰盛的慈爱。',
    keyVerse_en: 'I knew that you are a gracious God and merciful, slow to anger and abounding in steadfast love.',
    keyRef: '约拿书 4:2 / Jonah 4:2',
  },
  {
    id: 'micah',
    guideHref: '/old-testament/minor-prophets/micah',
    name_zh: '弥迦书',
    name_en: 'Micah',
    author_zh: '弥迦',
    author_en: 'Micah',
    date: '约公元前735-700年',
    date_en: 'c. 735–700 BC',
    theme_zh: '行公义、好怜悯——真正的敬虔',
    theme_en: 'Do Justice, Love Mercy — True Godliness',
    summary_zh: '弥迦向南北两国宣告审判与盼望，指出真正的敬虔不在外在礼仪，而在行公义、好怜悯、存谦卑的心与神同行。他也预言弥赛亚将生于伯利恒。',
    summary_en: 'Micah proclaims judgment and hope to both kingdoms, declaring that true godliness is not outward ritual but doing justice, loving mercy, and walking humbly with God. He also prophesies the Messiah\'s birth in Bethlehem.',
    keyVerse_zh: '世人哪，耶和华已指示你何为善。祂向你所要的是什么呢？只要你行公义，好怜悯，存谦卑的心，与你的神同行。',
    keyVerse_en: 'He has told you, O man, what is good; and what does the LORD require of you but to do justice, and to love kindness, and to walk humbly with your God?',
    keyRef: '弥迦书 6:8 / Micah 6:8',
  },
  {
    id: 'nahum',
    guideHref: '/old-testament/minor-prophets/nahum',
    name_zh: '那鸿书',
    name_en: 'Nahum',
    author_zh: '那鸿',
    author_en: 'Nahum',
    date: '约公元前663-612年',
    date_en: 'c. 663–612 BC',
    theme_zh: '神的公义审判——尼尼微的倾覆',
    theme_en: 'God\'s Righteous Judgment — The Fall of Nineveh',
    summary_zh: '那鸿书宣告曾经悔改又重新作恶的尼尼微城必被倾覆。神是忌邪施报的神，但对投靠祂的人却是坚固的保障。',
    summary_en: 'Nahum proclaims the doom of Nineveh, which had repented under Jonah but returned to wickedness. God is a jealous avenger, yet a stronghold for those who take refuge in Him.',
    keyVerse_zh: '耶和华本为善，在患难的日子为人的保障，并且认得那些投靠祂的人。',
    keyVerse_en: 'The LORD is good, a stronghold in the day of trouble; he knows those who take refuge in him.',
    keyRef: '那鸿书 1:7 / Nahum 1:7',
  },
  {
    id: 'habakkuk',
    guideHref: '/old-testament/minor-prophets/habakkuk',
    name_zh: '哈巴谷书',
    name_en: 'Habakkuk',
    author_zh: '哈巴谷',
    author_en: 'Habakkuk',
    date: '约公元前609-605年',
    date_en: 'c. 609–605 BC',
    theme_zh: '义人必因信得生',
    theme_en: 'The Righteous Shall Live by Faith',
    summary_zh: '哈巴谷大胆质问神为何容许恶人当道，神回答：审判必来，义人必因信得生。先知最终从质疑转为信靠，在苦难中欢喜赞美神。',
    summary_en: 'Habakkuk boldly questions God about why the wicked prosper. God answers: judgment is coming, and the righteous shall live by faith. The prophet moves from questioning to trust, rejoicing in God amid suffering.',
    keyVerse_zh: '义人必因信得生。',
    keyVerse_en: 'The righteous shall live by his faith.',
    keyRef: '哈巴谷书 2:4 / Habakkuk 2:4',
  },
  {
    id: 'zephaniah',
    guideHref: '/old-testament/minor-prophets/zephaniah',
    name_zh: '西番雅书',
    name_en: 'Zephaniah',
    author_zh: '西番雅',
    author_en: 'Zephaniah',
    date: '约公元前630年',
    date_en: 'c. 630 BC',
    theme_zh: '耶和华大日与余民的盼望',
    theme_en: 'The Great Day of the LORD and Hope for the Remnant',
    summary_zh: '西番雅书预言耶和华大而可畏的日子将审判犹大和列国，但神必保存谦卑寻求祂的余民。祂要在他们中间欢喜歌唱。',
    summary_en: 'Zephaniah prophesies the great Day of the LORD bringing judgment on Judah and the nations, yet God will preserve the humble remnant who seek Him. He will rejoice over them with singing.',
    keyVerse_zh: '耶和华你的神是施行拯救、大有能力的主。祂在你中间必因你欢欣喜乐，默然爱你，且因你喜乐而欢呼。',
    keyVerse_en: 'The LORD your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.',
    keyRef: '西番雅书 3:17 / Zephaniah 3:17',
  },
  {
    id: 'haggai',
    guideHref: '/old-testament/minor-prophets/haggai',
    name_zh: '哈该书',
    name_en: 'Haggai',
    author_zh: '哈该',
    author_en: 'Haggai',
    date: '约公元前520年',
    date_en: 'c. 520 BC',
    theme_zh: '重建圣殿——先求神的国',
    theme_en: 'Rebuild the Temple — Seek God\'s Kingdom First',
    summary_zh: '哈该激励归回的百姓重新建造圣殿，责备他们顾自己的房屋却忽略神的殿。当百姓先求神的国和神的义时，神应许与他们同在并赐福。',
    summary_en: 'Haggai urges the returned exiles to rebuild the temple, rebuking them for caring about their own houses while neglecting God\'s house. When the people seek God\'s kingdom first, He promises His presence and blessing.',
    keyVerse_zh: '万军之耶和华说：你们要省察自己的行为。',
    keyVerse_en: 'Thus says the LORD of hosts: Consider your ways.',
    keyRef: '哈该书 1:7 / Haggai 1:7',
  },
  {
    id: 'zechariah',
    guideHref: '/old-testament/minor-prophets/zechariah',
    name_zh: '撒迦利亚书',
    name_en: 'Zechariah',
    author_zh: '撒迦利亚',
    author_en: 'Zechariah',
    date: '约公元前520-480年',
    date_en: 'c. 520–480 BC',
    theme_zh: '弥赛亚君王的异象',
    theme_en: 'Visions of the Messianic King',
    summary_zh: '撒迦利亚书通过异象和预言鼓励重建圣殿的百姓，并包含大量弥赛亚预言：祂骑驴进耶路撒冷、被出卖三十块银子、被扎。',
    summary_en: 'Zechariah encourages the temple builders through visions and prophecies, containing many Messianic prophecies: the King riding on a donkey, betrayed for thirty pieces of silver, and pierced.',
    keyVerse_zh: '他们必仰望我，就是他们所扎的；必为我悲哀，如丧独生子。',
    keyVerse_en: 'They will look on me, on him whom they have pierced, they shall mourn for him, as one mourns for an only child.',
    keyRef: '撒迦利亚书 12:10 / Zechariah 12:10',
  },
  {
    id: 'malachi',
    guideHref: '/old-testament/minor-prophets/malachi',
    name_zh: '玛拉基书',
    name_en: 'Malachi',
    author_zh: '玛拉基',
    author_en: 'Malachi',
    date: '约公元前430年',
    date_en: 'c. 430 BC',
    theme_zh: '旧约的尾声——预备主的道路',
    theme_en: 'The Close of the Old Testament — Prepare the Way of the Lord',
    summary_zh: '玛拉基是旧约最后一位先知，责备百姓在敬拜和十一奉献上的敷衍，预言以利亚（施洗约翰）将来预备主的道路。此后是四百年的沉默，直到基督降生。',
    summary_en: 'Malachi, the last Old Testament prophet, rebukes the people\'s halfhearted worship and tithing, and prophesies that Elijah (John the Baptist) will come to prepare the way of the Lord. Then comes four hundred years of silence until Christ.',
    keyVerse_zh: '万军之耶和华说：我要差遣我的使者在我前面预备道路。',
    keyVerse_en: 'Behold, I send my messenger, and he will prepare the way before me.',
    keyRef: '玛拉基书 3:1 / Malachi 3:1',
  },
];

export default function MinorProphetsPage() {
  return (
    <BookList
      icon="📣"
      title_zh="小先知书"
      title_en="Minor Prophets"
      desc_zh={'十二位先知虽被称为\u201c小\u201d，篇幅较短，信息却同样震撼有力：悔改、公义、怜悯、审判与盼望，贯穿以色列历史的每一个关键时刻。'}
      desc_en={'The twelve "Minor" Prophets are shorter in length but equally powerful in message: repentance, justice, mercy, judgment, and hope — spanning every critical moment in Israel\'s history.'}
      gradient="from-sky-600 to-blue-800"
      books={books}
      backHref="/old-testament"
      backLabel="返回旧约导读 Back to Old Testament"
    />
  );
}
