import json

path = '/Users/suyan/clawd/projects/gospel-app/web/src/data/catechism_wlc.json'
d = json.load(open(path))

new_qs = [
    {
        "id": "wlc_101",
        "catechism": "westminster_larger",
        "number": 101,
        "question_zh": "十诫的序言是什么？",
        "question_en": "What is the preface to the Ten Commandments?",
        "answer_zh": "十诫的序言包含在以下话语中："我是耶和华你的神，曾将你从埃及地为奴之家领出来。"",
        "answer_en": "The preface to the Ten Commandments is contained in these words, I am the Lord thy God, which have brought thee out of the land of Egypt, out of the house of bondage.",
        "proof_texts": ["出埃及记 20:2"],
        "notes_zh": "十诫的序言表明神有权命令我们遵守祂的律法，因为祂是耶和华，是我们的神和救赎主。",
        "notes_en": "The preface to the Ten Commandments shows God's authority to command obedience, as He is the Lord, our God and Redeemer."
    },
    {
        "id": "wlc_102",
        "catechism": "westminster_larger",
        "number": 102,
        "question_zh": "十诫序言中"我是耶和华你的神"这句话，包含哪些特别的理由来遵行十诫的全部内容？",
        "question_en": "What is the sum of the four commandments which contain our duty to God?",
        "answer_zh": "十诫序言中"我是耶和华你的神"这句话所包含遵行十诫全部内容的特别理由是：因为神是耶和华，是自有永有的，是万有之源，所以我们当遵守祂全部的诫命；因为祂是我们的神，是立约的神，所以我们更当遵守祂的诫命。",
        "answer_en": "The sum of the four commandments containing our duty to God, is, to love the Lord our God with all our heart, and with all our soul, and with all our strength, and with all our mind.",
        "proof_texts": ["路加福音 10:27", "申命记 6:5"],
        "notes_zh": "前四条诫命总结为全心、全性、全力、全意爱主我们的神。",
        "notes_en": "The first four commandments are summed up in loving God with all our heart, soul, strength, and mind."
    },
    {
        "id": "wlc_103",
        "catechism": "westminster_larger",
        "number": 103,
        "question_zh": "后六条诫命的总纲是什么？",
        "question_en": "Which is the first commandment?",
        "answer_zh": "后六条诫命的总纲是爱人如己。",
        "answer_en": "The first commandment is, Thou shalt have no other gods before me.",
        "proof_texts": ["出埃及记 20:3"],
        "notes_zh": "第一条诫命要求我们认识并承认神是独一的真神，是我们的神，并据此敬拜荣耀祂。",
        "notes_en": "The first commandment requires us to know and acknowledge God as the only true God, and our God, and to worship and glorify Him accordingly."
    },
    {
        "id": "wlc_104",
        "catechism": "westminster_larger",
        "number": 104,
        "question_zh": "第一条诫命要求什么？",
        "question_en": "What are the duties required in the first commandment?",
        "answer_zh": "第一条诫命所要求的责任是：认识并承认神是独一的真神，是我们的神；据此来敬拜和荣耀祂；思念祂、默想祂、记念祂，尊崇祂、尊敬祂、赞美祂、呼求祂、信靠祂、仰望祂、以祂为乐、爱祂、渴慕祂、敬畏祂。",
        "answer_en": "The duties required in the first commandment are, the knowing and acknowledging of God to be the only true God, and our God; and to worship and glorify him accordingly, by thinking, meditating, remembering, highly esteeming, honoring, adoring, choosing, loving, desiring, fearing of him; believing him; trusting, hoping, delighting, rejoicing in him.",
        "proof_texts": ["历代志上 28:9", "申命记 26:17", "诗篇 95:6-7", "以赛亚书 45:20-25"],
        "notes_zh": "第一条诫命所要求的责任涵盖了我们对神应有的全部内在态度和外在行为。",
        "notes_en": "The duties of the first commandment encompass all inward attitudes and outward actions we owe to God."
    },
    {
        "id": "wlc_105",
        "catechism": "westminster_larger",
        "number": 105,
        "question_zh": "第一条诫命禁止什么？",
        "question_en": "What are the sins forbidden in the first commandment?",
        "answer_zh": "第一条诫命所禁止的罪是：无神论，否认或不承认有一位神存在；拜偶像，将本来属于神的敬拜或荣耀归给任何受造之物；不以心灵和诚实来思念、默想、记念、尊崇、尊敬、赞美、呼求、信靠、仰望神。",
        "answer_en": "The sins forbidden in the first commandment are, atheism, in denying or not having a God; idolatry, in having or worshipping more gods than one, or any with or instead of the true God; the not having and avouching him for God, and our God; the omission or neglect of anything due to him, required in this commandment.",
        "proof_texts": ["诗篇 14:1", "耶利米书 2:27-28", "罗马书 1:25"],
        "notes_zh": "第一条诫命禁止一切形式的无神论、偶像崇拜以及忽略对真神的敬拜。",
        "notes_en": "The first commandment forbids all forms of atheism, idolatry, and neglect of the worship due to the true God."
    },
    {
        "id": "wlc_106",
        "catechism": "westminster_larger",
        "number": 106,
        "question_zh": "在第一条诫命中，"在我面前"这几个字特别教训我们什么？",
        "question_en": "What are we specially taught by these words, before me, in the first commandment?",
        "answer_zh": ""在我面前"这几个字，在第一条诫命中特别教训我们：那无所不见的神注意到并极为不悦人有别的神来取代祂的地位。",
        "answer_en": "These words, before me, in the first commandment, teach us, that God, who seeth all things, taketh special notice of, and is much displeased with, the sin of having any other God.",
        "proof_texts": ["以西结书 8:5-6", "诗篇 44:20-21"],
        "notes_zh": ""在我面前"表明神的无所不在和全知，使得任何偶像崇拜在祂面前都无法隐藏。",
        "notes_en": "The words 'before me' highlight God's omnipresence and omniscience, making all idolatry inexcusable."
    },
    {
        "id": "wlc_107",
        "catechism": "westminster_larger",
        "number": 107,
        "question_zh": "第二条诫命是什么？",
        "question_en": "Which is the second commandment?",
        "answer_zh": "第二条诫命是："不可为自己雕刻偶像；也不可作什么形象，仿佛上天、下地和地底下、水中的百物。不可跪拜那些像；也不可侍奉它们；因为我耶和华你的神，是忌邪的神。恨我的，我必追讨他的罪，自父及子，直到三四代；爱我、守我诫命的，我必向他们发慈爱，直到千代。"",
        "answer_en": "The second commandment is, Thou shalt not make unto thee any graven image, or any likeness of anything that is in heaven above, or that is in the earth beneath, or that is in the water under the earth: Thou shalt not bow down thyself to them, nor serve them: for I the Lord thy God am a jealous God, visiting the iniquity of the fathers upon the children unto the third and fourth generation of them that hate me; and showing mercy unto thousands of them that love me, and keep my commandments.",
        "proof_texts": ["出埃及记 20:4-6"],
        "notes_zh": "第二条诫命关乎我们敬拜神的方式，禁止以任何形象来代表或敬拜神。",
        "notes_en": "The second commandment concerns the manner of worshipping God, forbidding the use of images in worship."
    },
    {
        "id": "wlc_108",
        "catechism": "westminster_larger",
        "number": 108,
        "question_zh": "第二条诫命要求什么？",
        "question_en": "What are the duties required in the second commandment?",
        "answer_zh": "第二条诫命所要求的责任是：领受、遵行并保守神在祂话语中所设立的一切宗教性的敬拜和典章，特别是祷告和奉基督的名感谢；宣读、传讲和听取神的话语；施行和领受圣礼；教会治理和惩戒。",
        "answer_en": "The duties required in the second commandment are, the receiving, observing, and keeping pure and entire, all such religious worship and ordinances as God hath instituted in his Word; particularly prayer and thanksgiving in the name of Christ; the reading, preaching, and hearing of the Word; the administration and receiving of the sacraments; church government and discipline.",
        "proof_texts": ["申命记 32:46-47", "马太福音 28:20", "使徒行传 2:42", "提摩太前书 4:13"],
        "notes_zh": "第二条诫命积极地要求我们遵守神所设立的一切敬拜方式和教会规矩。",
        "notes_en": "The second commandment positively requires us to observe all forms of worship and church order that God has instituted."
    },
    {
        "id": "wlc_109",
        "catechism": "westminster_larger",
        "number": 109,
        "question_zh": "第二条诫命禁止什么？",
        "question_en": "What are the sins forbidden in the second commandment?",
        "answer_zh": "第二条诫命所禁止的罪是：一切设计、劝告、命令、使用和赞同任何未经神设立的宗教敬拜；制作神三个位格中任何一个位格的形象，或制作在圣经中所记载的任何受造之物的形象，并加以敬拜或用以敬拜神；一切迷信行为。",
        "answer_en": "The sins forbidden in the second commandment are, all devising, counseling, commanding, using, and anywise approving, any religious worship not instituted by God himself; the making any representation of God, of all or of any of the three persons, either inwardly in our mind, or outwardly in any kind of image or likeness of any creature; all worshipping of it, or God in it or by it.",
        "proof_texts": ["申命记 12:30-32", "罗马书 1:22-23", "申命记 4:15-19"],
        "notes_zh": "第二条诫命禁止一切人为发明的敬拜方式和任何形式的偶像制造与崇拜。",
        "notes_en": "The second commandment forbids all man-made forms of worship and any making or worshipping of images."
    },
    {
        "id": "wlc_110",
        "catechism": "westminster_larger",
        "number": 110,
        "question_zh": "第二条诫命附加的理由是什么？",
        "question_en": "What are the reasons annexed to the second commandment, the more to enforce it?",
        "answer_zh": "附在第二条诫命上用以加强此诫命的理由，包含在以下话语中："因为我耶和华你的神，是忌邪的神。恨我的，我必追讨他的罪，自父及子，直到三四代；爱我、守我诫命的，我必向他们发慈爱，直到千代。"理由是：神对我们拥有主权，我们是属祂的；祂对自己的敬拜满怀热忱；祂必报应那些违反此诫命的人。",
        "answer_en": "The reasons annexed to the second commandment, the more to enforce it, contained in these words, For I the Lord thy God am a jealous God, visiting the iniquity of the fathers upon the children unto the third and fourth generation of them that hate me; and showing mercy unto thousands of them that love me, and keep my commandments; are, besides God's sovereignty over us, and propriety in us, his fervent zeal for his own worship, and his revengeful indignation against all false worship, as being a spiritual whoredom.",
        "proof_texts": ["出埃及记 20:5-6", "诗篇 95:2-3", "以西结书 16:26-27"],
        "notes_zh": "神对自己的敬拜满怀圣洁的嫉妒，假敬拜在祂眼中如同属灵的淫乱。",
        "notes_en": "God is zealous for pure worship; false worship is spiritual adultery in His sight."
    },
    {
        "id": "wlc_111",
        "catechism": "westminster_larger",
        "number": 111,
        "question_zh": "第三条诫命是什么？",
        "question_en": "Which is the third commandment?",
        "answer_zh": "第三条诫命是："不可妄称耶和华你神的名；因为妄称耶和华名的，耶和华必不以他为无罪。"",
        "answer_en": "The third commandment is, Thou shalt not take the name of the Lord thy God in vain: for the Lord will not hold him guiltless that taketh his name in vain.",
        "proof_texts": ["出埃及记 20:7"],
        "notes_zh": "第三条诫命保护神圣名的尊荣，禁止任何亵渎或轻率地使用神的名。",
        "notes_en": "The third commandment protects the honor of God's holy name, forbidding all profane or careless use of it."
    },
    {
        "id": "wlc_112",
        "catechism": "westminster_larger",
        "number": 112,
        "question_zh": "第三条诫命要求什么？",
        "question_en": "What is required in the third commandment?",
        "answer_zh": "第三条诫命所要求的是：神的名、称号、属性、典章、话语、圣礼、祷告、起誓、许愿、抽签以及神的作为和其他一切使神显为神的事物，都要圣洁而敬虔地加以使用。",
        "answer_en": "The third commandment requires, that the name of God, his titles, attributes, ordinances, the Word, sacraments, prayer, oaths, vows, lots, his works, and whatsoever else there is whereby he makes himself known, be holily and reverently used in thought, meditation, word, and writing.",
        "proof_texts": ["马太福音 6:9", "诗篇 68:4", "启示录 15:3-4", "传道书 5:1"],
        "notes_zh": "第三条诫命要求我们在思想、默想、言语和文字中圣洁敬虔地使用与神有关的一切事物。",
        "notes_en": "The third commandment requires holy and reverent use of everything by which God makes Himself known."
    },
    {
        "id": "wlc_113",
        "catechism": "westminster_larger",
        "number": 113,
        "question_zh": "第三条诫命禁止什么？",
        "question_en": "What are the sins forbidden in the third commandment?",
        "answer_zh": "第三条诫命所禁止的罪是：不恰当地使用神的名；滥用神的名、称号、属性、典章或作为；亵渎、假冒伪善的认信；发假誓或不必要的誓言；违犯合法的誓言和许愿；咒骂或对神的旨意和护理不满。",
        "answer_en": "The sins forbidden in the third commandment are, the not using of God's name as is required; and the abuse of it in an ignorant, vain, irreverent, profane, superstitious, or wicked mentioning or otherwise using his titles, attributes, ordinances, or works, by blasphemy, perjury; all sinful cursings, oaths, vows, and lots.",
        "proof_texts": ["玛拉基书 1:6-7", "利未记 19:12", "马太福音 5:34-37"],
        "notes_zh": "第三条诫命禁止一切亵渎、虚假的誓言、假冒为善和对神名的轻率使用。",
        "notes_en": "The third commandment forbids all blasphemy, false oaths, hypocrisy, and careless use of God's name."
    },
    {
        "id": "wlc_114",
        "catechism": "westminster_larger",
        "number": 114,
        "question_zh": "第三条诫命附加的理由是什么？",
        "question_en": "What reasons are annexed to the third commandment?",
        "answer_zh": "附在第三条诫命上的理由包含在以下话语中："因为妄称耶和华名的，耶和华必不以他为无罪。"也就是说，虽然违犯此诫命的人可能逃脱人的审判，但主我们的神必不容许他们逃脱祂公义的审判。",
        "answer_en": "The reasons annexed to the third commandment, in these words, The Lord will not hold him guiltless that taketh his name in vain, are, because he is the Lord and our God, therefore his name is not to be profaned, or any way abused by us; especially because he will be so far from acquitting and sparing the transgressors of this commandment, as that he will not suffer them to escape his righteous judgment.",
        "proof_texts": ["出埃及记 20:7", "申命记 28:58-59", "撒母耳记上 2:12", "撒母耳记上 3:13"],
        "notes_zh": "违犯第三条诫命的人无法逃脱神公义的审判。",
        "notes_en": "Those who violate the third commandment will not escape God's righteous judgment."
    },
    {
        "id": "wlc_115",
        "catechism": "westminster_larger",
        "number": 115,
        "question_zh": "第四条诫命是什么？",
        "question_en": "Which is the fourth commandment?",
        "answer_zh": "第四条诫命是："当记念安息日，守为圣日。六日要劳碌作你一切的工，但第七日是向耶和华你神当守的安息日。这一日你和你的儿女、仆婢、牲畜，并你城里寄居的客旅，无论何工都不可作。因为六日之内，耶和华造天、地、海和其中的万物，第七日便安息，所以耶和华赐福与安息日，定为圣日。"",
        "answer_en": "The fourth commandment is, Remember the sabbath day, to keep it holy. Six days shalt thou labor, and do all thy work: but the seventh day is the sabbath of the Lord thy God: in it thou shalt not do any work, thou, nor thy son, nor thy daughter, thy manservant, nor thy maidservant, nor thy cattle, nor thy stranger that is within thy gates: For in six days the Lord made heaven and earth, the sea, and all that in them is, and rested the seventh day: wherefore the Lord blessed the sabbath day, and hallowed it.",
        "proof_texts": ["出埃及记 20:8-11"],
        "notes_zh": "第四条诫命要求我们守安息日为圣，这是对神创造和救赎大工的纪念。",
        "notes_en": "The fourth commandment requires keeping the Sabbath holy, commemorating God's works of creation and redemption."
    },
    {
        "id": "wlc_116",
        "catechism": "westminster_larger",
        "number": 116,
        "question_zh": "第四条诫命要求什么？",
        "question_en": "What is required in the fourth commandment?",
        "answer_zh": "第四条诫命要求将神的话语中所指定的时间分别为圣归给祂，就是七日中的一整天，作为向祂守的圣安息日。从世界的起初到基督的复活是每周的末日，自基督复活以来是每周的第一日，就是基督徒的安息日，要一直持守到世界的末了，即新约中的安息日。",
        "answer_en": "The fourth commandment requires of all men the sanctifying or keeping holy to God such set times as he hath appointed in his Word, expressly one whole day in seven; which was the seventh day from the beginning of the world to the resurrection of Christ, and the first day of the week ever since, and so to continue to the end of the world; which is the Christian sabbath, and in the New Testament called The Lord's Day.",
        "proof_texts": ["创世记 2:2-3", "哥林多前书 16:1-2", "使徒行传 20:7", "启示录 1:10"],
        "notes_zh": "基督复活后，安息日从第七日改为第一日，即主日。",
        "notes_en": "After Christ's resurrection, the Sabbath was changed from the seventh to the first day of the week, the Lord's Day."
    },
    {
        "id": "wlc_117",
        "catechism": "westminster_larger",
        "number": 117,
        "question_zh": "安息日当怎样守为圣日？",
        "question_en": "How is the sabbath or the Lord's day to be sanctified?",
        "answer_zh": "安息日或主日的圣化是这样的：整天歇了自己的工，不但要休息那些在其他日子属于合法的属世职业和消遣，而且要把全部时间花在公开的和私下的敬拜神的事上，但为必要和怜悯的事则例外。",
        "answer_en": "The sabbath or Lord's day is to be sanctified by an holy resting all the day, not only from such works as are at all times sinful, but even from such worldly employments and recreations as are on other days lawful; and making it our delight to spend the whole time (except so much of it as is to be taken up in works of necessity and mercy) in the public and private exercises of God's worship.",
        "proof_texts": ["以赛亚书 58:13-14", "马太福音 12:1-13", "路加福音 4:16"],
        "notes_zh": "守安息日不仅是消极的休息，更是积极地以公开和私下的敬拜来度过这一天。",
        "notes_en": "Sabbath-keeping is not merely negative rest but positive engagement in public and private worship."
    },
    {
        "id": "wlc_118",
        "catechism": "westminster_larger",
        "number": 118,
        "question_zh": "为什么遵守安息日的命令是特别针对家长和其他上级的？",
        "question_en": "Why is the charge of keeping the sabbath more specially directed to governors of families, and other superiors?",
        "answer_zh": "遵守安息日的命令特别针对家长和其他上级，因为他们不但有义务自己遵守，还因为他们的权柄和影响力，他们要帮助在其管辖之下的人也遵守安息日。",
        "answer_en": "The charge of keeping the sabbath is more specially directed to governors of families, and other superiors, because they are bound not only to keep it themselves, but to see that it be observed by all those that are under their charge; and because they are prone ofttimes to hinder them by employments of their own.",
        "proof_texts": ["出埃及记 20:10", "尼希米记 13:15-17", "约书亚记 24:15"],
        "notes_zh": "家长和上级有责任确保在他们管辖下的人也遵守安息日。",
        "notes_en": "Heads of households and superiors are responsible for ensuring Sabbath observance by those under their charge."
    },
    {
        "id": "wlc_119",
        "catechism": "westminster_larger",
        "number": 119,
        "question_zh": "第四条诫命禁止什么？",
        "question_en": "What are the sins forbidden in the fourth commandment?",
        "answer_zh": "第四条诫命所禁止的罪是：完全忽略安息日当守的本分；或者懒散地、不注意地、无利益地履行这些本分；将安息日定为令人生厌的日子；在此日从事不必要的工作；或在此日说闲话或起空洞的想法。",
        "answer_en": "The sins forbidden in the fourth commandment are, all omissions of the duties required, all careless, negligent, and unprofitable performing of them, and being weary of them; all profaning the day by idleness, and doing that which is in itself sinful; and by all needless works, words, and thoughts, about our worldly employments and recreations.",
        "proof_texts": ["以西结书 22:26", "阿摩司书 8:5", "玛拉基书 1:13", "以赛亚书 58:13"],
        "notes_zh": "第四条诫命不仅禁止在安息日工作，也禁止懒惰、漫不经心地度过这一天。",
        "notes_en": "The fourth commandment forbids not only working on the Sabbath but also idle and careless observance."
    },
    {
        "id": "wlc_120",
        "catechism": "westminster_larger",
        "number": 120,
        "question_zh": "第四条诫命附加的理由是什么？",
        "question_en": "What are the reasons annexed to the fourth commandment, the more to enforce it?",
        "answer_zh": "附在第四条诫命上用以加强此诫命的理由是：神给了我们六天来从事自己的事务；祂宣称第七天是特别属于祂的；祂自己作了榜样；祂也赐福安息日。",
        "answer_en": "The reasons annexed to the fourth commandment, the more to enforce it, are taken from the equity of it, God allowing us six days of seven for our own affairs, and reserving but one for himself, in these words, Six days shalt thou labor, and do all thy work: from God's challenging a special propriety in that day, The seventh day is the sabbath of the Lord thy God: from the example of God, who in six days made heaven and earth, the sea, and all that in them is, and rested the seventh day: and from that blessing which God put upon that day, not only in sanctifying it to be a day for his service, but in ordaining it to be a means of blessing to us in our sanctifying it; Wherefore the Lord blessed the sabbath day, and hallowed it.",
        "proof_texts": ["出埃及记 20:9-11", "创世记 2:2-3"],
        "notes_zh": "神只取七分之一的时间归自己，却赐我们六天来处理自己的事务——这已是极大的恩慈。",
        "notes_en": "God reserves only one day in seven for Himself, granting us six for our own affairs — a display of great mercy."
    },
    {
        "id": "wlc_121",
        "catechism": "westminster_larger",
        "number": 121,
        "question_zh": "为什么诫命说"当记念安息日"？",
        "question_en": "Why is the word Remember set in the beginning of the fourth commandment?",
        "answer_zh": ""当记念"这个词放在第四条诫命的开头，一方面是因为对安息日的记念对于预备守安息有极大的帮助，另一方面是因为我们很容易忘记它。",
        "answer_en": "The word Remember is set in the beginning of the fourth commandment, partly, because of the great benefit of remembering it, we being thereby helped in our preparation to keep it, and, in keeping it, better to keep all the rest of the commandments, and to continue a thankful remembrance of the two great benefits of creation and redemption, which contain a short abridgment of religion; and partly, because we are very ready to forget it.",
        "proof_texts": ["出埃及记 20:8", "诗篇 103:2"],
        "notes_zh": ""当记念"这个词提醒我们，人天然倾向于忘记安息日。",
        "notes_en": "The word 'Remember' reminds us that we are naturally prone to forget the Sabbath."
    },
    {
        "id": "wlc_122",
        "catechism": "westminster_larger",
        "number": 122,
        "question_zh": "后六条诫命的总纲是什么？",
        "question_en": "What is the sum of the six commandments which contain our duty to man?",
        "answer_zh": "后六条诫命的总纲包含在以下话语中："要爱人如己。"",
        "answer_en": "The sum of the six commandments which contain our duty to man, is, to love our neighbor as ourselves, and to do to others what we would have them do to us.",
        "proof_texts": ["马太福音 22:39", "马太福音 7:12"],
        "notes_zh": "后六条诫命总结为爱人如己。",
        "notes_en": "The last six commandments are summed up in loving our neighbor as ourselves."
    },
    {
        "id": "wlc_123",
        "catechism": "westminster_larger",
        "number": 123,
        "question_zh": "第五条诫命是什么？",
        "question_en": "Which is the fifth commandment?",
        "answer_zh": "第五条诫命是："当孝敬父母，使你的日子在耶和华你神所赐你的地上得以长久。"",
        "answer_en": "The fifth commandment is, Honour thy father and thy mother: that thy days may be long upon the land which the Lord thy God giveth thee.",
        "proof_texts": ["出埃及记 20:12"],
        "notes_zh": "第五条诫命是后六条诫命中的第一条，涉及人与人之间的关系，以家庭关系为起点。",
        "notes_en": "The fifth commandment begins the second table of the law, starting with family relationships as foundational to all human relations."
    },
    {
        "id": "wlc_124",
        "catechism": "westminster_larger",
        "number": 124,
        "question_zh": "第五条诫命中"父母"是指谁？",
        "question_en": "Who are meant by father and mother in the fifth commandment?",
        "answer_zh": "第五条诫命中"父母"不仅是指血缘上的父母，也是指一切在年龄和恩赐上的长辈，特别是那些按照神的安排在我们之上有权柄的人，无论是在家庭中、教会中还是国家中。",
        "answer_en": "By father and mother, in the fifth commandment, are meant, not only natural parents, but all superiors in age and gifts; and especially such as, by God's ordinance, are over us in place of authority, whether in family, church, or commonwealth.",
        "proof_texts": ["箴言 23:22-25", "以弗所书 6:1-2", "提摩太前书 5:1-2", "创世记 4:20-22", "列王纪下 5:13"],
        "notes_zh": ""父母"在此指一切在年龄、恩赐和权柄上的长辈和上级。",
        "notes_en": "'Father and mother' here refers to all superiors in age, gifts, and authority."
    },
    {
        "id": "wlc_125",
        "catechism": "westminster_larger",
        "number": 125,
        "question_zh": "为什么称上级为父母？",
        "question_en": "Why are superiors styled Father and Mother?",
        "answer_zh": "称上级为父母，是要教导他们对下级履行一切本分，像亲生父母一样；也要使下级乐于而且甘心情愿地向他们回报尊敬，如同对待自己的亲生父母一样。",
        "answer_en": "Superiors are styled Father and Mother, both to teach them in all duties toward their inferiors, like natural parents, to express love and tenderness to them, according to their several relations; and to work inferiors to a greater willingness and cheerfulness in performing their duties to their superiors, as to their parents.",
        "proof_texts": ["以弗所书 6:4", "帖撒罗尼迦前书 2:7-8", "哥林多前书 4:14-16"],
        "notes_zh": "将上级称为父母，既要求上级如父母般关爱下级，也要求下级甘心尊敬上级。",
        "notes_en": "Calling superiors 'father and mother' teaches both parental care from superiors and willing respect from inferiors."
    },
    {
        "id": "wlc_126",
        "catechism": "westminster_larger",
        "number": 126,
        "question_zh": "第五条诫命的一般范围是什么？",
        "question_en": "What is the general scope of the fifth commandment?",
        "answer_zh": "第五条诫命的一般范围是：按照各人不同的关系，作为上级、下级或同辈，履行彼此之间应尽的本分。",
        "answer_en": "The general scope of the fifth commandment is, the performance of those duties which we mutually owe in our several relations, as inferiors, superiors, or equals.",
        "proof_texts": ["以弗所书 5:21", "彼得前书 2:17", "罗马书 12:10"],
        "notes_zh": "第五条诫命不仅涉及上下级关系，也涉及同辈之间的相互尊重。",
        "notes_en": "The fifth commandment addresses not only hierarchical relationships but also mutual duties among equals."
    },
    {
        "id": "wlc_127",
        "catechism": "westminster_larger",
        "number": 127,
        "question_zh": "下级对上级当尽什么尊敬？",
        "question_en": "What is the honor that inferiors owe to their superiors?",
        "answer_zh": "下级对上级当尽的尊敬是：心里尊重他们、在祷告和感谢中纪念他们、效法他们的美德和恩典、甘心顺服他们合法的命令和劝告、对他们的纠正忠诚顺从、在他们行善做得好的时候效忠和捍卫他们的人和权威。",
        "answer_en": "The honor which inferiors owe to their superiors is, all due reverence in heart, word, and behavior; prayer and thanksgiving for them; imitation of their virtues and graces; willing obedience to their lawful commands and counsels; due submission to their corrections; fidelity to, defense and maintenance of their persons and authority.",
        "proof_texts": ["玛拉基书 1:6", "箴言 31:28", "以弗所书 6:1-3", "希伯来书 13:17"],
        "notes_zh": "对上级的尊敬包括内心的尊重、祷告中的纪念和行为上的顺服。",
        "notes_en": "Honor to superiors includes inward reverence, prayerful remembrance, and behavioral obedience."
    },
    {
        "id": "wlc_128",
        "catechism": "westminster_larger",
        "number": 128,
        "question_zh": "下级对上级的罪是什么？",
        "question_en": "What are the sins of inferiors against their superiors?",
        "answer_zh": "下级对上级的罪是：忽略对他们应尽的本分；嫉妒、藐视和反叛他们的人和地位；咒诅、嘲弄和一切叛逆不恭的行为。",
        "answer_en": "The sins of inferiors against their superiors are, all neglect of the duties required toward them; envying at, contempt of, and rebellion against their persons and places, in their lawful counsels, commands, and corrections; cursing, mocking, and all such refractory and scandalous carriage.",
        "proof_texts": ["马太福音 15:4-6", "撒母耳记上 8:7", "撒母耳记下 15:1-12", "出埃及记 21:15"],
        "notes_zh": "下级对上级的罪包括忽略责任、藐视、叛逆和一切不恭敬的行为。",
        "notes_en": "The sins of inferiors include neglect of duty, contempt, rebellion, and all disrespectful conduct."
    },
    {
        "id": "wlc_129",
        "catechism": "westminster_larger",
        "number": 129,
        "question_zh": "上级对下级当尽什么？",
        "question_en": "What is required of superiors towards their inferiors?",
        "answer_zh": "上级对下级当尽的是：按照他们从神所领受的权柄和各人的关系，爱他们、为他们祷告和祝福；教导、劝告他们；称赞和奖赏行善的人、责备做恶的人；保护他们、供应他们生活所需。",
        "answer_en": "It is required of superiors, according to that power they receive from God, and that relation wherein they stand, to love, pray for, and bless their inferiors; to instruct, counsel, and admonish them; countenancing, commending, and rewarding such as do well; and discountenancing, reproving, and chastising such as do ill; protecting, and providing for them all things necessary for soul and body.",
        "proof_texts": ["歌罗西书 3:19", "帖撒罗尼迦前书 5:12", "彼得前书 3:7", "提摩太前书 5:8"],
        "notes_zh": "上级的责任是以爱和智慧来管理下级，供应他们灵魂和身体一切所需。",
        "notes_en": "Superiors are to govern with love and wisdom, providing for both spiritual and physical needs of those under them."
    },
    {
        "id": "wlc_130",
        "catechism": "westminster_larger",
        "number": 130,
        "question_zh": "上级的罪是什么？",
        "question_en": "What are the sins of superiors?",
        "answer_zh": "上级的罪是：疏忽对下级当尽的本分或行任何违反其本分的事；不正当地寻求自己的荣耀、安逸、利益或享乐；命令下级做不合法的事或违反神旨意的事；以不义的方式激怒下级或使他们灰心丧志。",
        "answer_en": "The sins of superiors are, besides the neglect of the duties required of them, an inordinate seeking of themselves, their own glory, ease, profit, or pleasure; commanding things unlawful, or not in the power of inferiors to perform; counseling, encouraging, or favoring them in that which is evil; dissuading, discouraging, or discountenancing them in that which is good.",
        "proof_texts": ["以西结书 34:2-4", "腓立比书 2:21", "出埃及记 5:10-19", "马太福音 23:2-4"],
        "notes_zh": "上级的罪包括忽略职责、自私自利、命令不义之事和打击下级的善行。",
        "notes_en": "The sins of superiors include neglect of duty, selfishness, commanding unlawful things, and discouraging good."
    },
    {
        "id": "wlc_131",
        "catechism": "westminster_larger",
        "number": 131,
        "question_zh": "同辈彼此当尽什么？",
        "question_en": "What are the duties of equals?",
        "answer_zh": "同辈彼此当尽的是：彼此看重对方的尊严和价值；以各人看别人比自己强；为别人的恩赐和进步而欢喜，如同为自己的一样。",
        "answer_en": "The duties of equals are, to regard the dignity and worth of each other, in giving honor to go one before another; and to rejoice in each other's gifts and advancement, as their own.",
        "proof_texts": ["罗马书 12:10", "腓立比书 2:3", "罗马书 12:15-16"],
        "notes_zh": "同辈之间当互相尊重、彼此推让，为对方的成就而欢喜。",
        "notes_en": "Equals should show mutual respect, deference, and joy in each other's achievements."
    },
    {
        "id": "wlc_132",
        "catechism": "westminster_larger",
        "number": 132,
        "question_zh": "同辈的罪是什么？",
        "question_en": "What are the sins of equals?",
        "answer_zh": "同辈的罪是：藐视别人的恩赐和成就；嫉妒别人或因别人的升高而不满；妄自尊大。",
        "answer_en": "The sins of equals are, besides the neglect of the duties required, the undervaluing of the worth, envying the gifts, grieving at the advancement of prosperity one of another; and usurping preeminence one over another.",
        "proof_texts": ["提摩太后书 3:3", "使徒行传 7:9", "约翰三书 1:9", "路加福音 22:24"],
        "notes_zh": "同辈之间的罪包括藐视、嫉妒和争夺地位。",
        "notes_en": "The sins of equals include contempt, envy, and striving for preeminence over one another."
    },
    {
        "id": "wlc_133",
        "catechism": "westminster_larger",
        "number": 133,
        "question_zh": "第五条诫命附加的理由是什么？",
        "question_en": "What is the reason annexed to the fifth commandment, the more to enforce it?",
        "answer_zh": "附在第五条诫命上用以加强此诫命的理由包含在以下话语中："使你的日子在耶和华你神所赐你的地上得以长久。"这是神对一切遵守此诫命的人的长寿和兴旺的应许。",
        "answer_en": "The reason annexed to the fifth commandment, in these words, That thy days may be long upon the land which the Lord thy God giveth thee, is an express promise of long life and prosperity, as far as it shall serve for God's glory and their own good, to all such as keep this commandment.",
        "proof_texts": ["出埃及记 20:12", "以弗所书 6:2-3", "申命记 5:16"],
        "notes_zh": "遵守第五条诫命的人将得到长寿和兴旺的应许。",
        "notes_en": "Those who keep the fifth commandment receive a promise of long life and prosperity."
    },
    {
        "id": "wlc_134",
        "catechism": "westminster_larger",
        "number": 134,
        "question_zh": "第六条诫命是什么？",
        "question_en": "Which is the sixth commandment?",
        "answer_zh": "第六条诫命是："不可杀人。"",
        "answer_en": "The sixth commandment is, Thou shalt not kill.",
        "proof_texts": ["出埃及记 20:13"],
        "notes_zh": "第六条诫命保护人的生命，因为人是按照神的形象被造的。",
        "notes_en": "The sixth commandment protects human life, as man is made in the image of God."
    },
    {
        "id": "wlc_135",
        "catechism": "westminster_larger",
        "number": 135,
        "question_zh": "第六条诫命要求什么？",
        "question_en": "What are the duties required in the sixth commandment?",
        "answer_zh": "第六条诫命所要求的是：一切合法的努力来保护我们自己和他人的生命；抵制一切谋杀的意图；约束过度的情绪；节制饮食和药品的使用；保护内心的平静和灵魂的耐心；追求和平的言论和行为；忍耐承受和饶恕伤害；以善报恶；安慰和救济受苦的人。",
        "answer_en": "The duties required in the sixth commandment are, all careful studies, and lawful endeavors, to preserve the life of ourselves and others by resisting all thoughts and purposes, subduing all passions, and avoiding all occasions, temptations, and practices, which tend to the unjust taking away the life of any; by just defense thereof against violence, patient bearing of the hand of God, quietness of mind, cheerfulness of spirit; a sober use of meat, drink, medicine, sleep, labor, and recreations.",
        "proof_texts": ["以弗所书 5:28-29", "列王纪上 18:4", "箴言 22:24-25", "马太福音 5:22", "罗马书 12:18-20"],
        "notes_zh": "第六条诫命不仅禁止杀人，更积极要求我们保护一切人的生命。",
        "notes_en": "The sixth commandment not only forbids killing but positively requires preserving life."
    },
    {
        "id": "wlc_136",
        "catechism": "westminster_larger",
        "number": 136,
        "question_zh": "第六条诫命禁止什么？",
        "question_en": "What are the sins forbidden in the sixth commandment?",
        "answer_zh": "第六条诫命所禁止的罪是：夺取我们自己或他人的生命，但合法的公开处刑、正义的战争或正当防卫除外；忽略或剥夺保护生命的合法手段；罪恶的怒气、仇恨、嫉妒、报复的欲望；一切过度的情绪和扰乱心灵安宁的忧虑；不节制地饮食和使用药品；挑衅的言语、压迫、争竞。",
        "answer_en": "The sins forbidden in the sixth commandment are, all taking away the life of ourselves, or of others, except in case of public justice, lawful war, or necessary defense; the neglecting or withdrawing the lawful and necessary means of preservation of life; sinful anger, hatred, envy, desire of revenge; all excessive passions, distracting cares; immoderate use of meat, drink, labor, and recreations; provoking words, oppression, quarreling.",
        "proof_texts": ["创世记 9:6", "马太福音 5:21-22", "箴言 14:30", "约翰一书 3:15", "利未记 19:17"],
        "notes_zh": "第六条诫命禁止一切直接或间接的杀害行为，包括怒气、仇恨和报复。",
        "notes_en": "The sixth commandment forbids all direct or indirect destruction of life, including anger, hatred, and revenge."
    },
    {
        "id": "wlc_137",
        "catechism": "westminster_larger",
        "number": 137,
        "question_zh": "第七条诫命是什么？",
        "question_en": "Which is the seventh commandment?",
        "answer_zh": "第七条诫命是："不可奸淫。"",
        "answer_en": "The seventh commandment is, Thou shalt not commit adultery.",
        "proof_texts": ["出埃及记 20:14"],
        "notes_zh": "第七条诫命保护婚姻的神圣和人的贞洁。",
        "notes_en": "The seventh commandment protects the sanctity of marriage and personal chastity."
    },
    {
        "id": "wlc_138",
        "catechism": "westminster_larger",
        "number": 138,
        "question_zh": "第七条诫命要求什么？",
        "question_en": "What are the duties required in the seventh commandment?",
        "answer_zh": "第七条诫命所要求的是：保守我们自己和他人在身体和心灵上的贞洁；警醒守护眼目和一切感官；节制、保持贞洁的交往、穿着谦虚得体、婚姻是神圣的，已婚之人当彼此相爱、同住；勤劳工作、节制饮食。",
        "answer_en": "The duties required in the seventh commandment are, chastity in body, mind, affections, words, and behavior; and the preservation of it in ourselves and others; watchfulness over the eyes and all the senses; temperance, keeping of chaste company, modesty in apparel; marriage by those that have not the gift of continency, conjugal love, and cohabitation; diligent labor in our callings; and avoiding of all occasions of uncleanness.",
        "proof_texts": ["哥林多前书 7:2-3", "帖撒罗尼迦前书 4:4-5", "约伯记 31:1", "箴言 5:18-19", "提摩太前书 2:9"],
        "notes_zh": "第七条诫命积极要求我们在身心上保守贞洁，以及在婚姻关系中互相尽忠。",
        "notes_en": "The seventh commandment positively requires chastity in body and mind, and faithfulness in marriage."
    },
    {
        "id": "wlc_139",
        "catechism": "westminster_larger",
        "number": 139,
        "question_zh": "第七条诫命禁止什么？",
        "question_en": "What are the sins forbidden in the seventh commandment?",
        "answer_zh": "第七条诫命所禁止的罪是：除了忽略所要求的本分之外，还包括奸淫、淫乱、强奸、乱伦、鸡奸和一切违反自然的淫行；一切不洁的想像、念头、意图和情欲；一切败坏的或肮脏的言语交流；不端庄的容貌、不谦虚的衣着；禁止合法的和允许不合法的婚姻；容许、经营或出入妓院；陷入受约束的独身生活。",
        "answer_en": "The sins forbidden in the seventh commandment, besides the neglect of the duties required, are, adultery, fornication, rape, incest, sodomy, and all unnatural lusts; all unclean imaginations, thoughts, purposes, and affections; all corrupt or filthy communications, or listening thereunto; wanton looks, impudent or light behavior, immodest apparel; prohibiting of lawful, and dispensing with unlawful marriages; allowing, tolerating, keeping of stews, and resorting to them.",
        "proof_texts": ["马太福音 5:28", "以弗所书 5:3-4", "罗马书 13:13", "马可福音 6:18", "提摩太前书 4:3"],
        "notes_zh": "第七条诫命禁止一切形式的不洁，包括思想、言语和行为上的不洁。",
        "notes_en": "The seventh commandment forbids all forms of impurity in thought, word, and deed."
    },
    {
        "id": "wlc_140",
        "catechism": "westminster_larger",
        "number": 140,
        "question_zh": "第八条诫命是什么？",
        "question_en": "Which is the eighth commandment?",
        "answer_zh": "第八条诫命是："不可偷盗。"",
        "answer_en": "The eighth commandment is, Thou shalt not steal.",
        "proof_texts": ["出埃及记 20:15"],
        "notes_zh": "第八条诫命保护人的财产权利。",
        "notes_en": "The eighth commandment protects the right to property."
    },
    {
        "id": "wlc_141",
        "catechism": "westminster_larger",
        "number": 141,
        "question_zh": "第八条诫命要求什么？",
        "question_en": "What are the duties required in the eighth commandment?",
        "answer_zh": "第八条诫命所要求的是：在合法方面诚实地获得、保管和使用我们自己和他人的财物及产业的合法手段。具体说来就是：节俭、勤劳工作；公平交易；偿还欠债；归还被盗或被拿走的东西；适度地饮食、穿着和生活；按照各人的能力和需要慷慨施舍。",
        "answer_en": "The duties required in the eighth commandment are, truth, faithfulness, and justice in contracts and commerce between man and man; rendering to everyone his due; restitution of goods unlawfully detained from the right owners thereof; giving and lending freely, according to our abilities, and the necessities of others; moderation of our judgments, wills, and affections concerning worldly goods; a provident care and study to get, keep, use, and dispose these things which are necessary and convenient for the sustentation of our nature.",
        "proof_texts": ["利未记 6:2-5", "申命记 25:13-15", "路加福音 6:30-38", "提摩太前书 6:6-9"],
        "notes_zh": "第八条诫命积极要求我们诚实劳动、公平交易、慷慨施舍。",
        "notes_en": "The eighth commandment positively requires honest labor, fair dealing, and generous giving."
    },
    {
        "id": "wlc_142",
        "catechism": "westminster_larger",
        "number": 142,
        "question_zh": "第八条诫命禁止什么？",
        "question_en": "What are the sins forbidden in the eighth commandment?",
        "answer_zh": "第八条诫命所禁止的罪是：偷盗、抢劫、掳人为奴和窝藏赃物；欺诈交易中短斤缺两、伪造度量衡；挪移地界；在信托和交易中不公正不忠实；敲诈勒索、强取豪夺；放高利贷、贿赂、为虚假的诉讼；贪心不足、高估和过度看重属世之物；嫉妒别人的兴旺；懒惰、挥霍浪费。",
        "answer_en": "The sins forbidden in the eighth commandment, besides the neglect of the duties required, are, theft, robbery, man-stealing, and receiving anything that is stolen; fraudulent dealing, false weights and measures, removing landmarks, injustice and unfaithfulness in contracts between man and man, or in matters of trust; oppression, extortion, usury, bribery, vexatious lawsuits, unjust enclosures and depopulations; engrossing commodities to enhance the price; unlawful callings, and all other unjust or sinful ways of taking or withholding from our neighbor what belongs to him, or of enriching ourselves.",
        "proof_texts": ["以弗所书 4:28", "箴言 11:1", "诗篇 37:21", "路加福音 16:10-12", "帖撒罗尼迦前书 4:6"],
        "notes_zh": "第八条诫命禁止一切不正当获取他人财物的方式。",
        "notes_en": "The eighth commandment forbids all unjust ways of acquiring or withholding others' property."
    },
    {
        "id": "wlc_143",
        "catechism": "westminster_larger",
        "number": 143,
        "question_zh": "第九条诫命是什么？",
        "question_en": "Which is the ninth commandment?",
        "answer_zh": "第九条诫命是："不可作假见证陷害人。"",
        "answer_en": "The ninth commandment is, Thou shalt not bear false witness against thy neighbor.",
        "proof_texts": ["出埃及记 20:16"],
        "notes_zh": "第九条诫命保护人的名誉和真理。",
        "notes_en": "The ninth commandment protects reputation and truth."
    },
    {
        "id": "wlc_144",
        "catechism": "westminster_larger",
        "number": 144,
        "question_zh": "第九条诫命要求什么？",
        "question_en": "What are the duties required in the ninth commandment?",
        "answer_zh": "第九条诫命所要求的是：在人与人之间维护和促进真理，以及我们自己和别人的好名声，特别是在作见证的时候；按照真理说话，只说真话，发自内心，诚实、自由、清楚、完全地说；为真理站立，乐意接受它、热心爱慕它；爱惜和关怀别人的好名声，维护和促进它。",
        "answer_en": "The duties required in the ninth commandment are, the preserving and promoting of truth between man and man, and the good name of our neighbor, as well as our own; appearing and standing for the truth; and from the heart, sincerely, freely, clearly, and fully, speaking the truth, and only the truth, in matters of judgment and justice, and in all other things whatsoever; a charitable esteem of our neighbors; loving, desiring, and rejoicing in their good name.",
        "proof_texts": ["撒迦利亚书 8:16", "约翰三书 1:12", "箴言 14:5", "哥林多后书 1:17-18", "以弗所书 4:25"],
        "notes_zh": "第九条诫命积极要求我们说真话、维护他人的名声。",
        "notes_en": "The ninth commandment positively requires truthful speech and protection of others' good name."
    },
    {
        "id": "wlc_145",
        "catechism": "westminster_larger",
        "number": 145,
        "question_zh": "第九条诫命禁止什么？",
        "question_en": "What are the sins forbidden in the ninth commandment?",
        "answer_zh": "第九条诫命所禁止的罪是：一切损害真理和我们自己或他人好名声的事，特别是在法庭审判中作假见证和教唆别人作假见证；故意隐瞒真理、在不义之事上沉默；在本当说话的时候不为真理和他人的好名声站出来；破坏承诺、更改为善的决心；无根据的猜疑；嫉妒别人的恩赐和才能；散布流言蜚语、诽谤中伤。",
        "answer_en": "The sins forbidden in the ninth commandment are, all prejudicing the truth, and the good name of our neighbors, as well as our own, especially in public judicature; giving false evidence, suborning false witnesses, wittingly appearing and pleading for an evil cause, outfacing and overbearing the truth; passing unjust sentence, calling evil good, and good evil; rewarding the wicked according to the work of the righteous, and the righteous according to the work of the wicked; forgery, concealing the truth, undue silence in a just cause.",
        "proof_texts": ["箴言 19:5", "利未记 19:15", "以赛亚书 5:20", "箴言 25:23", "箴言 26:24-25"],
        "notes_zh": "第九条诫命禁止一切损害真理和他人名誉的言行。",
        "notes_en": "The ninth commandment forbids all speech and action that harms truth or others' reputation."
    },
    {
        "id": "wlc_146",
        "catechism": "westminster_larger",
        "number": 146,
        "question_zh": "第十条诫命是什么？",
        "question_en": "Which is the tenth commandment?",
        "answer_zh": "第十条诫命是："不可贪恋人的房屋；也不可贪恋人的妻子、仆婢、牛驴，并他一切所有的。"",
        "answer_en": "The tenth commandment is, Thou shalt not covet thy neighbor's house, thou shalt not covet thy neighbor's wife, nor his manservant, nor his maidservant, nor his ox, nor his ass, nor anything that is thy neighbor's.",
        "proof_texts": ["出埃及记 20:17"],
        "notes_zh": "第十条诫命深入人心内部，禁止一切贪恋的念头。",
        "notes_en": "The tenth commandment reaches into the heart, forbidding all covetous desires."
    },
    {
        "id": "wlc_147",
        "catechism": "westminster_larger",
        "number": 147,
        "question_zh": "第十条诫命要求什么？",
        "question_en": "What are the duties required in the tenth commandment?",
        "answer_zh": "第十条诫命所要求的是：对我们自己的光景完全满足；对邻舍有整个灵魂中仁慈爱心的倾向；使得我们心灵中的一切动态和情感都指向而且促成他一切所有的益处。",
        "answer_en": "The duties required in the tenth commandment are, such a full contentment with our own condition, and such a charitable frame of the whole soul toward our neighbor, as that all our inward motions and affections touching him, tend unto, and further all that good which is his.",
        "proof_texts": ["希伯来书 13:5", "提摩太前书 6:6", "罗马书 12:15", "腓立比书 2:4", "提摩太前书 1:5"],
        "notes_zh": "第十条诫命要求内心的知足和对邻舍真诚的善意。",
        "notes_en": "The tenth commandment requires inner contentment and genuine goodwill toward our neighbor."
    },
    {
        "id": "wlc_148",
        "catechism": "westminster_larger",
        "number": 148,
        "question_zh": "第十条诫命禁止什么？",
        "question_en": "What are the sins forbidden in the tenth commandment?",
        "answer_zh": "第十条诫命所禁止的罪是：对我们自己的境况不满；嫉妒和忧愁别人的好处；一切不合秩序的感动和内心欲望的倾向，指向属于别人的任何东西。",
        "answer_en": "The sins forbidden in the tenth commandment are, discontentment with our own estate; envying and grieving at the good of our neighbor, together with all inordinate motions and affections to anything that is his.",
        "proof_texts": ["列王纪上 21:4", "以斯帖记 5:13", "哥林多前书 10:10", "加拉太书 5:26", "歌罗西书 3:5"],
        "notes_zh": "第十条诫命禁止一切不满足、嫉妒和对他人财物的贪恋。",
        "notes_en": "The tenth commandment forbids all discontentment, envy, and coveting of what belongs to others."
    },
    {
        "id": "wlc_149",
        "catechism": "westminster_larger",
        "number": 149,
        "question_zh": "有谁能完全遵守神的诫命？",
        "question_en": "Is any man able perfectly to keep the commandments of God?",
        "answer_zh": "自从堕落以来，没有任何人能够在今生完全遵守神的诫命，而是每天在思想、言语和行为上违犯诫命。",
        "answer_en": "No man is able, either of himself, or by any grace received in this life, perfectly to keep the commandments of God; but doth daily break them in thought, word, and deed.",
        "proof_texts": ["传道书 7:20", "创世记 6:5", "创世记 8:21", "雅各书 3:2-13", "约翰一书 1:8"],
        "notes_zh": "自堕落以来，无人能完全遵守神的诫命，这显示我们对基督救赎恩典的绝对需要。",
        "notes_en": "Since the fall, no one can perfectly keep God's commandments, showing our absolute need for Christ's redeeming grace."
    },
    {
        "id": "wlc_150",
        "catechism": "westminster_larger",
        "number": 150,
        "question_zh": "所有违犯神律法的罪都同样可憎吗？",
        "question_en": "Are all transgressions of the law of God equally heinous in themselves, and in the sight of God?",
        "answer_zh": "所有违犯神律法的罪并不是同样可憎的；有些罪本身和因为几种加重情节，在神看来比其他的罪更为可恨。",
        "answer_en": "All transgressions of the law of God are not equally heinous; but some sins in themselves, and by reason of several aggravations, are more heinous in the sight of God than others.",
        "proof_texts": ["约翰福音 19:11", "以西结书 8:6", "以西结书 8:13", "以西结书 8:15", "约翰一书 5:16"],
        "notes_zh": "虽然一切罪都得罪神，但有些罪因其性质和加重情节而比其他罪更为严重。",
        "notes_en": "While all sins offend God, some are more heinous than others due to their nature and aggravating circumstances."
    }
]

d.extend(new_qs)
json.dump(d, open(path, 'w'), ensure_ascii=False, indent=2)
print(f'Total: {len(d)}')
